config/routes.rb
Rails.application.routes.draw do
  resources :albums

  root 'albums#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :album_songs
  has_many :songs, through: :album_songs
end

app/models/album_song.rb
class AlbumSong < ActiveRecord::Base
  belongs_to :album 
  belongs_to :song
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  belongs_to :song
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :album_songs
  has_many :albums, through: :album_songs
end

app/controllers/albums_controller.rb
class AlbumsController  <ApplicationController

  def index
    @albums = Album.all
  end
  
  def show
    @album = Album.find(params[:id])
  end

 private
  def album_params
    params.require(:album).permit(:name, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController  <ApplicationController

  def index
    @songs = Song.all
  end
  
  def show
    @song = Song.find(params[:id])
  end

 private
  def song_params
    params.require(:song).permit(:name, :genre_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<h2>The Album Index Page</h2>
<div>
  <% @albums.each do |album| %>
    <li><%= link_to(album.name, album_path(album.id))%></li>
  <% end %>
</div>

app/views/albums/show.html.erb
<h2>The Album Show Page</h2>
<div>
  <%= @album.name %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav>
    <li><%= link_to('Albums',albums_path) %></li>
  </nav>
</header>

<%= yield %>

</body>
</html>

app/views/songs/index.html.erb
<h2>The Songs Index Page</h2>
<div>
  <% @songs.each do |song| %>
    <li><%= link_to(song.name, song_path(song.id))%></li>
  <% end %>
</div>